### ISSUE TITLE
from where will I get './dataset/val.txt' file ?/

### ISSUE THREAD

**Issue by ChinmayKalyankar** [tangzhenyu/SemanticSegmentation_DL#6]
![error ss2](https://user-images.githubusercontent.com/13298739/37765723-fc203da8-2dea-11e8-80e3-416dc3cf8220.png)

**Comment by tangzhenyu** [comment]
Fixed this issus,  the default is to use VOC2012 dataset, so you can rerun the command. Since the pretrained model is a large file, I have not yet upload the model which is a necessary file for running test option.
